version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn compile package install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/pokeman-1.0.0-SNAPSHOT.jar
